import Head from "next/head";
import Image from "next/image";
import Main from "./Main";
import Hero from "./Hero";



export default function Home() {
  return (
    <div>
      <Head>
        <title>StockCheck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
        <Main />
      
      
    </div>
  );
}
