import Head from "next/head";
import Image from "next/image";
import Hero from "./Hero";
import Login from "./Login";

import StockSearch from "./StockSearch";

export default function Home() {
  return (
    <div>
      <Head>
        <title>StockCheck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
        <StockSearch />
      
      
    </div>
  );
}
